name: CI
on:
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push API Gateway image to Amazon ECR
        working-directory: ./application/services/custom_services/apigateway
        run: |
          pwd
          docker build -t ${{ steps.login-ecr.outputs.registry }}/geppetto-generatedcode-apigateway:0.0.1 .
          docker push ${{ steps.login-ecr.outputs.registry }}/geppetto-generatedcode-apigateway:0.0.1

