name: CI
on:
  push:
    branches: main
jobs:
  Upload_FrontEnd_S3:
    runs-on: ubuntu-latest
    steps:
    - name: Check the  branch
      uses: actions/checkout@v2
    - name: Installing the Node and its dependies
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Installing node modules
      working-directory: ./application/client/desktop/ramtest
      run: |
        npm install -g @angular/cli
        npm i node-sass@4.8.3
        npm i @ng-select/ng-select
        npm i 
        ng build --configuration=production
    - name: Uploading dist files into the S3 bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ram-geppetto-test
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        SOURCE_DIR: "application/client/desktop/ramtest/dist/ramtest"
